---
# tasks for netplan_bridge

- name: End the play for hosts that don't run Ubuntu 18.04 or greater.
  meta: end_host
  when: not ansible_distribution == 'Ubuntu' or ansible_distribution_major_version | int < 18

- name: Capture existing configurations
  find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _netplan_configs

- name: Remove exisiting configurations
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ _netplan_configs['files'] }}"
  when:
    - item['path'] != netplan_config_file

- name: Register status of /etc/netplan/ansible-config.yaml
  stat:
    path: "{{ netplan_config_file }}"
  register: ansible_netplan_config

- name: Install Netplan configuration file
  template:
    src: templates/ansible-config.yaml.j2
    dest: "{{ netplan_config_file }}"
  notify: netplan generate config
  when: not ansible_netplan_config.stat.exists

- name: Run handlers
  meta: flush_handlers